### Obtener todos los Tiendas.
GET http://localhost:8000/stores

### Obtener Tienda por ID.
GET http://localhost:8000/stores/1

### Crear Tienda.
POST http://localhost:8000/stores
Content-Type: application/json

{
   "name": "Amazon",
   "description": "Tienda de Tiendas",
   "userId": 2
}

### Actualizar Tienda.
PUT http://localhost:8000/stores/1
Content-Type: application/json

{
   "warehouseAddress": "Calle 123"
}

### Borrar Tienda.
DELETE http://localhost:8000/stores/1