### Obtener todos los Usuarios.
GET http://localhost:8000/users

### Obtener Usuario por ID.
GET http://localhost:8000/users/1

### Obtener Ordenes del usuario
GET http://localhost:8000/users/2/orders

### Crear Usuario.
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Raine",
    "type": "Marketplace User",
    "email": "raine@email.com",
    "shippingAddress": "Calle falsa 123"
}

### Actualizar libro.
PUT http://localhost:8000/users/1
Content-Type: application/json

{
    "name": "",
    "type": "",
    "email": "",
    "shippingAddress": ""
}

### Borrar libro.
DELETE http://localhost:8000/users/1