### Get Users
GET http://localhost:8000/users

### Obtener usuario por ID.
GET http://localhost:8000/users/3

### Create User
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "Miguel Perez",
    "type": "marketplace user",
    "email": "mrodriguez@gmail.com",
    "shipping_address": "Calle falsa 123"
}

### Actualizar usuario.
PUT http://localhost:8000/users/3
Content-Type: application/json

{
    "type": "Marketplace User",
    "shipping_address": "downtown california"
}

### Borrar usuario.
DELETE http://localhost:8000/users/1